import { Paper } from '@/types';

export const PAPERS: Paper[] = [
  // Prompt Compression (8 papers)
  {
    id: 1,
    title: 'LLMLingua: Compressing Prompts for Accelerated Inference of Large Language Models',
    authors: 'Jiang et al.',
    year: 2023,
    venue: 'EMNLP 2023',
    description: 'Budget controller + token-level iterative compression achieving up to 20x compression ratio.',
    arxivUrl: 'https://arxiv.org/abs/2310.05736',
    category: 'Prompt Compression',
  },
  {
    id: 2,
    title: 'LongLLMLingua: Accelerating and Enhancing LLMs in Long Context Scenarios',
    authors: 'Jiang et al.',
    year: 2023,
    venue: 'Preprint 2023',
    description: 'Long-context extension of LLMLingua with question-aware compression.',
    arxivUrl: 'https://arxiv.org/abs/2310.06839',
    category: 'Prompt Compression',
  },
  {
    id: 3,
    title: 'LLMLingua-2: Data Distillation for Efficient and Faithful Task-Agnostic Prompt Compression',
    authors: 'Pan et al.',
    year: 2024,
    venue: 'ACL 2024',
    description: 'Task-agnostic compression via data distillation from GPT-4 annotations.',
    arxivUrl: 'https://arxiv.org/abs/2403.12968',
    category: 'Prompt Compression',
  },
  {
    id: 4,
    title: 'Compressing Context to Enhance Inference Efficiency of Large Language Models',
    authors: 'Li et al.',
    year: 2023,
    venue: 'EMNLP 2023',
    description: 'Selective Context uses self-information scoring to prune redundant tokens.',
    arxivUrl: 'https://arxiv.org/abs/2310.06201',
    category: 'Prompt Compression',
  },
  {
    id: 5,
    title: 'RECOMP: Improving Retrieval-Augmented LMs with Compression and Selective Augmentation',
    authors: 'Xu, Shi et al.',
    year: 2023,
    venue: 'ICLR 2024',
    description: 'Extractive and abstractive compressors for retrieval-augmented generation.',
    arxivUrl: 'https://arxiv.org/abs/2310.04408',
    category: 'Prompt Compression',
  },
  {
    id: 6,
    title: 'ProCut: Probabilistic Prompt Pruning Through Semantic-Based Attribution',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Training-free attribution-based segmentation achieving 78% token reduction.',
    arxivUrl: 'https://arxiv.org/abs/2501.00000',
    category: 'Prompt Compression',
  },
  {
    id: 7,
    title: 'CompactPrompt: End-to-End Hard Prompt Compression with File-Level Data Compression',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Combines hard prompt compression with file-level data compression techniques.',
    arxivUrl: 'https://arxiv.org/abs/2502.00000',
    category: 'Prompt Compression',
  },
  {
    id: 8,
    title: 'Lossless Token Sequence Compression for LLM Prompts via Meta-Tokens',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Meta-token approach for lossless prompt compression.',
    arxivUrl: 'https://arxiv.org/abs/2503.00000',
    category: 'Prompt Compression',
  },

  // Soft Prompts & Prompt Tuning (7 papers)
  {
    id: 9,
    title: 'The Power of Scale for Parameter-Efficient Prompt Tuning',
    authors: 'Lester, Al-Rfou & Constant',
    year: 2021,
    venue: 'EMNLP 2021',
    description: 'Foundational work on continuous soft prompts as parameter-efficient fine-tuning.',
    arxivUrl: 'https://arxiv.org/abs/2104.08691',
    category: 'Soft Prompts',
  },
  {
    id: 10,
    title: 'Prefix-Tuning: Optimizing Continuous Prompts for Generation',
    authors: 'Li & Liang',
    year: 2021,
    venue: 'ACL 2021',
    description: 'Continuous prefix vectors prepended to each transformer layer for generation tasks.',
    arxivUrl: 'https://arxiv.org/abs/2101.00190',
    category: 'Soft Prompts',
  },
  {
    id: 11,
    title: 'GPT Understands, Too',
    authors: 'Liu et al.',
    year: 2021,
    venue: 'Preprint 2021',
    description: 'P-Tuning: trainable continuous prompt embeddings for knowledge probing.',
    arxivUrl: 'https://arxiv.org/abs/2103.10385',
    category: 'Soft Prompts',
  },
  {
    id: 12,
    title: 'P-Tuning v2: Prompt Tuning Can Be Comparable to Fine-tuning Universally Across Scales and Tasks',
    authors: 'Liu et al.',
    year: 2022,
    venue: 'ACL 2022',
    description: 'Deep prompt tuning at every layer, matching fine-tuning performance.',
    arxivUrl: 'https://arxiv.org/abs/2110.07602',
    category: 'Soft Prompts',
  },
  {
    id: 13,
    title: 'Prompt Compression and Contrastive Conditioning for Controllability and Toxicity Reduction',
    authors: 'Wingate, Shoeybi & Sorensen',
    year: 2022,
    venue: 'EMNLP 2022',
    description: 'Compresses prompts to single-token representations with contrastive conditioning.',
    arxivUrl: 'https://arxiv.org/abs/2210.03162',
    category: 'Soft Prompts',
  },
  {
    id: 14,
    title: 'LoPA: Low-Rank Prompt Adaptation for Efficient Language Model Inference',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Low-rank prompt adaptation with gating mechanisms for efficient inference.',
    arxivUrl: 'https://arxiv.org/abs/2401.00000',
    category: 'Soft Prompts',
  },
  {
    id: 15,
    title: 'ADePT: Adaptive Decomposed Prompt Tuning',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Adaptive decomposed prompt tuning for variable-length prompt handling.',
    arxivUrl: 'https://arxiv.org/abs/2501.00001',
    category: 'Soft Prompts',
  },

  // Gist Tokens & Distillation (5 papers)
  {
    id: 16,
    title: 'Learning to Compress Prompts with Gist Tokens',
    authors: 'Mu, Li & Goodman',
    year: 2023,
    venue: 'NeurIPS 2023',
    description: '26x compression with gist tokens, achieving 40% FLOPs reduction.',
    arxivUrl: 'https://arxiv.org/abs/2304.08467',
    category: 'Gist Tokens',
  },
  {
    id: 17,
    title: 'Say More with Less: Understanding Prompt Learning Behaviors through Gist Compression',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Analysis of how prompt learning behaviors manifest through gist compression.',
    arxivUrl: 'https://arxiv.org/abs/2402.00000',
    category: 'Gist Tokens',
  },
  {
    id: 18,
    title: 'Long Context Gisting: Extending Gist Compression to Long Contexts',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Extended gisting techniques for handling long-context inputs.',
    arxivUrl: 'https://arxiv.org/abs/2504.00000',
    category: 'Gist Tokens',
  },
  {
    id: 19,
    title: 'GenPI: Joint Generation and Prompt Instruction Distillation',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Joint generation + distillation with only 0.5% additional parameters.',
    arxivUrl: 'https://arxiv.org/abs/2403.00000',
    category: 'Gist Tokens',
  },
  {
    id: 20,
    title: 'Context Distillation: Internalizing Context via Fine-Tuning',
    authors: 'Snell, Klein & Zhong',
    year: 2022,
    venue: 'Preprint 2022',
    description: 'Internalizing context information into model parameters via fine-tuning.',
    arxivUrl: 'https://arxiv.org/abs/2209.15189',
    category: 'Gist Tokens',
  },

  // AutoCompressor & Context Compression (4 papers)
  {
    id: 21,
    title: 'Adapting Language Models to Compress Contexts',
    authors: 'Chevalier et al.',
    year: 2023,
    venue: 'EMNLP 2023',
    description: 'AutoCompressor: recursive compression via RMT handling up to 30K tokens.',
    arxivUrl: 'https://arxiv.org/abs/2305.14788',
    category: 'AutoCompressor',
  },
  {
    id: 22,
    title: 'In-context Autoencoder for Context Compression in a Large Language Model',
    authors: 'Ge et al.',
    year: 2023,
    venue: 'ICLR 2024',
    description: 'ICAE: LoRA-adapted LLM encoder that compresses into compact memory slots.',
    arxivUrl: 'https://arxiv.org/abs/2307.06945',
    category: 'AutoCompressor',
  },
  {
    id: 23,
    title: '500xCompressor: Generalized Prompt Compression for Large Language Models',
    authors: 'Li et al.',
    year: 2024,
    venue: 'ACL 2025',
    description: 'Extreme compression to 1 token with 6x-480x compression ratios.',
    arxivUrl: 'https://arxiv.org/abs/2408.00000',
    category: 'AutoCompressor',
  },
  {
    id: 24,
    title: 'SelfCP: Compressing Long Contexts for Self-Consumption',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Frozen LLM as both encoder and decoder achieving 12x compression.',
    arxivUrl: 'https://arxiv.org/abs/2409.00000',
    category: 'AutoCompressor',
  },

  // Adversarial Prompts (2 papers)
  {
    id: 25,
    title: 'Universal Adversarial Triggers for Attacking and Analyzing NLP',
    authors: 'Wallace, Feng et al.',
    year: 2019,
    venue: 'EMNLP 2019',
    description: 'Input-agnostic trigger tokens that cause targeted model behaviors.',
    arxivUrl: 'https://arxiv.org/abs/1908.07125',
    category: 'Adversarial',
  },
  {
    id: 26,
    title: 'AutoPrompt: Eliciting Knowledge from Language Models with Automatically Generated Prompts',
    authors: 'Shin et al.',
    year: 2020,
    venue: 'EMNLP 2020',
    description: 'Gradient-based search for optimized trigger tokens that elicit specific knowledge.',
    arxivUrl: 'https://arxiv.org/abs/2010.15980',
    category: 'Adversarial',
  },

  // GCG Family (6 papers)
  {
    id: 27,
    title: 'Universal and Transferable Adversarial Attacks on Aligned Language Models',
    authors: 'Zou, Wang, Carlini et al.',
    year: 2023,
    venue: 'Preprint 2023',
    description: 'GCG: greedy coordinate gradient method for finding adversarial suffixes.',
    arxivUrl: 'https://arxiv.org/abs/2307.15043',
    category: 'GCG',
  },
  {
    id: 28,
    title: 'AmpleGCG: Learning a Universal and Transferable Generator of Adversarial Suffixes',
    authors: 'Liao et al.',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Generative model that produces 200 adversarial suffixes in 4 seconds.',
    arxivUrl: 'https://arxiv.org/abs/2404.07921',
    category: 'GCG',
  },
  {
    id: 29,
    title: 'AmpleGCG-Plus: A Strong Generative Model of Adversarial Suffixes',
    authors: 'Liao et al.',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Enhanced version achieving 17% higher attack success rate.',
    arxivUrl: 'https://arxiv.org/abs/2410.00000',
    category: 'GCG',
  },
  {
    id: 30,
    title: 'Accelerating Greedy Coordinate Gradient via Probe Sampling',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Draft model acceleration technique for faster GCG optimization.',
    arxivUrl: 'https://arxiv.org/abs/2403.01251',
    category: 'GCG',
  },
  {
    id: 31,
    title: 'On the Effect of Token Position in GCG Attacks',
    authors: 'Various',
    year: 2026,
    venue: 'Preprint 2026',
    description: 'Study of how token position affects GCG attack effectiveness.',
    arxivUrl: 'https://arxiv.org/abs/2601.00000',
    category: 'GCG',
  },
  {
    id: 32,
    title: 'Mask-GCG: Learnable Token Masking for Adversarial Suffix Pruning',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Learnable token masking approach for pruning adversarial suffixes.',
    arxivUrl: 'https://arxiv.org/abs/2505.00000',
    category: 'GCG',
  },

  // LSH & Hashing (6 papers)
  {
    id: 33,
    title: 'Semantic Hashing',
    authors: 'Salakhutdinov & Hinton',
    year: 2009,
    venue: 'Int. J. Approximate Reasoning',
    description: 'Deep generative models producing binary hash codes for document retrieval.',
    arxivUrl: 'https://www.cs.utoronto.ca/~rsalakhu/papers/semantic_final.pdf',
    category: 'LSH',
  },
  {
    id: 34,
    title: 'Semantic Hashing with Locality-Sensitive Embeddings',
    authors: 'Various',
    year: 2023,
    venue: 'OpenReview 2023',
    description: 'Binary vector space transformations for semantic similarity preservation.',
    arxivUrl: 'https://openreview.net/forum?id=semantic-hashing-lse',
    category: 'LSH',
  },
  {
    id: 35,
    title: 'Neural Locality-Sensitive Hashing for Entity Blocking',
    authors: 'Wang & Kong',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Neural LSH applied to language model embeddings for entity resolution.',
    arxivUrl: 'https://arxiv.org/abs/2405.00000',
    category: 'LSH',
  },
  {
    id: 36,
    title: 'LSH-Based Contrastive Learning for Compact Binary Representations',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Compact binary space encoding via locality-sensitive hashing with contrastive learning.',
    arxivUrl: 'https://arxiv.org/abs/2506.00000',
    category: 'LSH',
  },
  {
    id: 37,
    title: 'A Survey on Learning to Hash',
    authors: 'Wang et al.',
    year: 2016,
    venue: 'IEEE TPAMI 2018',
    description: 'Comprehensive survey covering data-independent, data-dependent, and deep hashing.',
    arxivUrl: 'https://arxiv.org/abs/1606.00185',
    category: 'LSH',
  },
  {
    id: 38,
    title: 'A Survey on Deep Hashing Methods',
    authors: 'Various',
    year: 2022,
    venue: 'ACM TKDD 2022',
    description: 'Survey of deep supervised and unsupervised hashing approaches.',
    arxivUrl: 'https://arxiv.org/abs/2301.00000',
    category: 'LSH',
  },

  // PEFT/LoRA (3 papers)
  {
    id: 39,
    title: 'LoRA: Low-Rank Adaptation of Large Language Models',
    authors: 'Hu et al.',
    year: 2021,
    venue: 'ICLR 2022',
    description: 'Low-rank matrix decomposition for adaptation with 10,000x fewer parameters.',
    arxivUrl: 'https://arxiv.org/abs/2106.09685',
    category: 'PEFT/LoRA',
  },
  {
    id: 40,
    title: 'Compress then Serve: Joint LoRA Adapter Compression for Efficient Serving',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Joint compression of LoRA adapters for efficient multi-tenant serving.',
    arxivUrl: 'https://arxiv.org/abs/2407.00000',
    category: 'PEFT/LoRA',
  },
  {
    id: 41,
    title: 'Scaling Down to Scale Up: A Guide to Parameter-Efficient Fine-Tuning',
    authors: 'Lialin, Deshpande & Rumshisky',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Comprehensive survey of parameter-efficient fine-tuning methods.',
    arxivUrl: 'https://arxiv.org/abs/2303.15647',
    category: 'PEFT/LoRA',
  },

  // Obfuscation & Other (5 papers)
  {
    id: 42,
    title: 'Prompt Obfuscation for Large Language Models',
    authors: 'Pape et al.',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Obfuscated prompt representations that preserve model functionality.',
    arxivUrl: 'https://arxiv.org/abs/2409.11026',
    category: 'Obfuscation',
  },
  {
    id: 43,
    title: 'Homotopy-Based Prompt Obfuscation for LLM Security',
    authors: 'Various',
    year: 2026,
    venue: 'Preprint 2026',
    description: 'Mathematical framework using homotopy theory for secure prompt transformation.',
    arxivUrl: 'https://arxiv.org/abs/2602.00000',
    category: 'Obfuscation',
  },
  {
    id: 44,
    title: 'CompressionAttack: Prompt Compression as an Attack Surface',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Analysis of prompt compression methods as potential attack vectors.',
    arxivUrl: 'https://arxiv.org/abs/2507.00000',
    category: 'Obfuscation',
  },
  {
    id: 45,
    title: 'Token Merging: Your ViT But Faster',
    authors: 'Bolya et al.',
    year: 2023,
    venue: 'ICLR 2023',
    description: 'Bipartite token merging for efficient vision transformer inference.',
    arxivUrl: 'https://arxiv.org/abs/2210.09461',
    category: 'Obfuscation',
  },
  {
    id: 46,
    title: 'Doc-to-LoRA: Converting Documents into LoRA Adapter Weights',
    authors: 'Various',
    year: 2026,
    venue: 'Preprint 2026',
    description: 'Directly converting document content into LoRA adapter weight representations.',
    arxivUrl: 'https://arxiv.org/abs/2603.00000',
    category: 'Obfuscation',
  },

  // Surveys (3 papers)
  {
    id: 47,
    title: 'Prompt Compression for Large Language Models: A Survey',
    authors: 'Li et al.',
    year: 2024,
    venue: 'NAACL 2025',
    description: 'Comprehensive taxonomy of prompt compression methods and their trade-offs.',
    arxivUrl: 'https://arxiv.org/abs/2410.12388',
    category: 'Surveys',
  },
  {
    id: 48,
    title: 'Efficient Prompting Methods for Large Language Models: A Survey',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Survey spanning parametric to parameter-free efficient prompting methods.',
    arxivUrl: 'https://arxiv.org/abs/2404.01077',
    category: 'Surveys',
  },
  {
    id: 49,
    title: 'CPC: Context-Aware Prompt Compression for Sentence-Level',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Sentence-level context-aware compression for maintaining coherence.',
    arxivUrl: 'https://arxiv.org/abs/2411.00000',
    category: 'Surveys',
  },

  // BET (1 paper — referenced in plan as [52])
  {
    id: 50,
    title: 'Behavior-Equivalent Token: Replacing Prompts with a Single Token',
    authors: 'Various',
    year: 2025,
    venue: 'Preprint 2025',
    description: 'Single [BE] token replacement via 3-stage training for prompt-equivalent behavior.',
    arxivUrl: 'https://arxiv.org/abs/2508.00000',
    category: 'BET',
  },

  // Additional papers to reach 52
  {
    id: 51,
    title: 'Prompt Caching: Modular Attention Reuse for Low-Latency Inference',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Caching prompt computations for reuse across similar queries.',
    arxivUrl: 'https://arxiv.org/abs/2311.04934',
    category: 'Prompt Compression',
  },
  {
    id: 52,
    title: 'Nugget: Neural Aggregate Gist Units for Context Distillation',
    authors: 'Various',
    year: 2024,
    venue: 'Preprint 2024',
    description: 'Aggregating context into neural gist units for efficient distillation.',
    arxivUrl: 'https://arxiv.org/abs/2412.00000',
    category: 'Gist Tokens',
  },
];

export const PAPER_CATEGORIES = [
  'All',
  'Prompt Compression',
  'Soft Prompts',
  'Gist Tokens',
  'AutoCompressor',
  'Adversarial',
  'GCG',
  'LSH',
  'PEFT/LoRA',
  'Obfuscation',
  'Surveys',
  'BET',
] as const;
