import { Technique } from '@/types';

export const TECHNIQUES: Technique[] = [
  {
    id: 'bet',
    name: 'Behavior-Equivalent Tokens (BET)',
    shortName: 'BET',
    description: 'Replace entire prompts with a single special [BE] token that produces equivalent model behavior. A 3-stage training process: token embedding initialization, behavior alignment via distillation, and fine-tuning for output fidelity.',
    steps: [
      'Initialize a new [BE] token embedding in the model vocabulary',
      'Train embedding via distillation: minimize KL-divergence between original prompt and [BE] token outputs',
      'Fine-tune with contrastive loss to ensure behavioral equivalence',
      'Validate that [BE] token produces semantically equivalent responses',
    ],
    pros: [
      'Maximum compression — entire prompt to single token',
      'True behavioral equivalence when well-trained',
      'Fast inference after training',
    ],
    cons: [
      'Requires model fine-tuning (not plug-and-play)',
      'One [BE] token per prompt (not reusable)',
      'Training can be computationally expensive',
    ],
    applicability: 'Best for high-value, frequently-used prompts where training cost is justified by repeated use.',
    paperRefs: [52],
    metrics: {
      compressionRatio: '~1000:1',
      fidelity: '92-96%',
      speed: 'Fast (inference)',
      reversibility: 'Very Low',
    },
  },
  {
    id: 'soft-prompts',
    name: 'Lossy Encoding via Soft Prompts',
    shortName: 'Soft Prompts',
    description: 'Optimize continuous embedding vectors (soft prompts) that, when prepended to model input, replicate the behavior of the original discrete prompt. The soft prompt exists in embedding space and has no human-readable form.',
    steps: [
      'Tokenize the original prompt and get target model outputs',
      'Initialize random continuous vectors in embedding space',
      'Optimize vectors via gradient descent to minimize output divergence',
      'Compress optimized vectors into a compact representation',
    ],
    pros: [
      'High fidelity — operates in model\'s native embedding space',
      'Adjustable compression via number of soft tokens',
      'Well-studied with strong theoretical foundations',
    ],
    cons: [
      'Requires gradient access to the model',
      'Not transferable across different models',
      'Soft prompts are opaque — no interpretability',
    ],
    applicability: 'Ideal when you have model access and need high-fidelity compression with privacy.',
    paperRefs: [2, 3, 4, 5, 6, 7, 8, 36, 37, 38, 39],
    metrics: {
      compressionRatio: '10-50:1',
      fidelity: '90-98%',
      speed: 'Slow (training)',
      reversibility: 'Low',
    },
  },
  {
    id: 'lsh',
    name: 'Locality-Sensitive Hashing (LSH)',
    shortName: 'LSH',
    description: 'Map prompt embeddings to binary hash codes using locality-sensitive hash functions. Similar prompts map to the same or nearby hash buckets, enabling fast lookup of pre-computed responses.',
    steps: [
      'Encode the prompt into a dense embedding vector',
      'Apply random hyperplane projections (LSH family)',
      'Generate binary hash code from projection signs',
      'Look up nearest pre-computed response in hash table',
    ],
    pros: [
      'Extremely fast lookup — O(1) for exact match',
      'No model fine-tuning required',
      'Well-understood theoretical guarantees',
    ],
    cons: [
      'Lossy — similar but different prompts may collide',
      'Requires pre-computed response database',
      'Hash quality depends on embedding model',
    ],
    applicability: 'Best for high-throughput systems with a known set of prompt patterns.',
    paperRefs: [9, 10, 11, 12, 13, 14],
    metrics: {
      compressionRatio: '100-500:1',
      fidelity: '70-85%',
      speed: 'Very Fast',
      reversibility: 'Very Low',
    },
  },
  {
    id: 'gist-tokens',
    name: 'Hybrid Distillation with Gist Tokens',
    shortName: 'Gist Tokens',
    description: 'Compress prompts into a small set of "gist" tokens through knowledge distillation. The model learns to extract the behavioral essence of a prompt into these compact representations.',
    steps: [
      'Define a set of learnable gist token positions',
      'Train with attention masking: gist tokens attend to full prompt, output attends only to gist tokens',
      'Distill knowledge from full prompt into gist representations',
      'At inference, replace full prompt with gist tokens only',
    ],
    pros: [
      'Strong compression with good fidelity (26x demonstrated)',
      '40% FLOPs reduction in inference',
      'Works with instruction-tuned models',
    ],
    cons: [
      'Requires model modification (attention masking)',
      'Training is compute-intensive',
      'May struggle with very long or complex prompts',
    ],
    applicability: 'Excellent for system prompts and repeated instructions where training cost is amortized.',
    paperRefs: [15, 16, 17, 18, 19],
    metrics: {
      compressionRatio: '26:1',
      fidelity: '88-94%',
      speed: 'Medium',
      reversibility: 'Low',
    },
  },
  {
    id: 'adversarial',
    name: 'Adversarial Prompts',
    shortName: 'Adversarial',
    description: 'Find token sequences without clear semantic meaning that nonetheless trigger specific model outputs. These "nonsense" sequences exploit the model\'s learned associations to produce targeted behavior.',
    steps: [
      'Define target model output (from original prompt)',
      'Initialize random token sequence',
      'Use gradient-based search to find tokens that maximize target output probability',
      'Validate adversarial prompt produces equivalent behavior',
    ],
    pros: [
      'Resulting prompt is unintelligible — strong privacy',
      'Can achieve very specific output targeting',
      'Demonstrates fundamental properties of LLM behavior',
    ],
    cons: [
      'Computationally expensive search process',
      'Fragile — small model changes break the prompt',
      'Ethical concerns about adversarial techniques',
    ],
    applicability: 'Research-focused. Demonstrates that LLM behavior can be triggered by non-semantic tokens.',
    paperRefs: [20, 21],
    metrics: {
      compressionRatio: 'Variable',
      fidelity: '75-90%',
      speed: 'Very Slow',
      reversibility: 'Very Low',
    },
  },
  {
    id: 'soft-prompt-optimization',
    name: 'Soft Prompt Optimization',
    shortName: 'SPO',
    description: 'Optimize continuous embedding vectors to replicate prompt behavior using various training objectives. Unlike basic soft prompts, SPO uses advanced optimization techniques including contrastive learning and adaptive decomposition.',
    steps: [
      'Select optimization objective (KL-divergence, contrastive, or hybrid)',
      'Initialize embeddings via prompt token averaging',
      'Apply low-rank adaptation (LoPA) or decomposed tuning (ADePT)',
      'Iteratively optimize until convergence',
    ],
    pros: [
      'State-of-the-art fidelity with advanced objectives',
      'Low-rank methods reduce parameter count',
      'Adaptive techniques handle variable-length prompts',
    ],
    cons: [
      'Requires significant training infrastructure',
      'Hyperparameter-sensitive optimization',
      'Model-specific — no cross-model transfer',
    ],
    applicability: 'When maximum fidelity is required and compute resources are available.',
    paperRefs: [2, 3, 4, 5, 6, 7, 8],
    metrics: {
      compressionRatio: '20-100:1',
      fidelity: '93-98%',
      speed: 'Slow',
      reversibility: 'Low',
    },
  },
  {
    id: 'gcg',
    name: 'Greedy Coordinate Gradient (GCG)',
    shortName: 'GCG',
    description: 'Iterative discrete optimization algorithm that finds token sequences producing specific model outputs. At each step, compute gradients w.r.t. token embeddings, identify promising substitutions, and greedily select the best replacement.',
    steps: [
      'Initialize with random or prompt-derived token suffix',
      'Compute gradient of loss w.r.t. each token embedding',
      'Generate top-k candidate substitutions per position',
      'Evaluate candidates in batch and select best improvement',
      'Repeat until convergence or budget exhausted',
    ],
    pros: [
      'Works with discrete tokens (no continuous embeddings needed)',
      'Can find surprisingly effective short sequences',
      'Active research area with rapid improvements',
    ],
    cons: [
      'Very computationally expensive (minutes per prompt)',
      'Resulting sequences are gibberish — no interpretability',
      'Sensitive to model version and hyperparameters',
    ],
    applicability: 'Research into adversarial robustness and the nature of LLM prompt sensitivity.',
    paperRefs: [22, 23, 24, 25, 26, 27],
    metrics: {
      compressionRatio: '5-20:1',
      fidelity: '80-92%',
      speed: 'Very Slow',
      reversibility: 'Very Low',
    },
  },
];
